### ISSUE TITLE
Building touche fails while using yay or paru on arch linux

### ISSUE THREAD

**Issue by itsRaCl** [JoseExposito/touche#83]
I don't know if this is the right place to ask this
But when i'm trying to install touche it fails while giving this error 

```
[11/16] Generating bundle/build-application-bundle with a custom command
FAILED: bundle/com.github.joseexposito.touche.js
/usr/bin/node /home/racl/temp/touche/src/touche-2.0.6/bundle/scripts/build.js /home/racl/temp/touche/src/touche-2.0.6 /home/racl/temp/touche/src/touche-2.0.6/build/bundle plain com.github.joseexposito.touche false /usr/share/touchegg/touchegg.conf
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at BulkUpdateDecorator.hashFactory (/home/racl/temp/touche/src/touche-2.0.6/node_modules/webpack/lib/util/createHash.js:155:18)
    at BulkUpdateDecorator.digest (/home/racl/temp/touche/src/touche-2.0.6/node_modules/webpack/lib/util/createHash.js:80:21)
    at /home/racl/temp/touche/src/touche-2.0.6/node_modules/webpack/lib/DefinePlugin.js:595:38
    at Hook.eval [as call] (eval at create (/home/racl/temp/touche/src/touche-2.0.6/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:100:1)
    at Hook.CALL_DELEGATE [as _call] (/home/racl/temp/touche/src/touche-2.0.6/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/home/racl/temp/touche/src/touche-2.0.6/node_modules/webpack/lib/Compiler.js:1053:26)
    at /home/racl/temp/touche/src/touche-2.0.6/node_modules/webpack/lib/Compiler.js:1097:29
    at Hook.eval [as callAsync] (eval at create (/home/racl/temp/touche/src/touche-2.0.6/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v19.0.1
[12/16] Compiling C++ object subprojects/libtouche/libtouche.so.0.p/touche.cpp.o
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...

```
I have tried using yay, paru and also manually building the package from source

**Comment by JoseExposito** [comment]
Hi! Could you try with the latest code present in the `master` branch, please? It should be fixed.

**Comment by itsRaCl** [comment]
Yeah sure!
I'll installed it by manually building the package
I'll uninstall it and then let you know

Sorry for the late reply I got busy with college stuff

**Comment by itsRaCl** [comment]
I tried re installing using the aur package
It still fails for me
But cloning the master branch and installing it manually works

**Comment by JoseExposito** [comment]
Cool, closing the issue then as it is fixed upstream. I'll try to release a new version tomorrow so the fix is available on AUR.
